name       : ocamlbuild
version    : 0.14.2
release    : 7
source     :
    - https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.2.tar.gz : 62d2dab6037794c702a83ac584a7066d018cf1645370d1f3d5764c2b458791b1
license    : LGPL-2.1
component  : programming.tools
summary    : OCamlbuild is a generic build tool, that has built-in rules for building OCaml library and programs.
description: |
    OCamlbuild is a generic build tool, that has built-in rules for building OCaml library and programs.
builddeps  :
    - ocaml
rundeps    :
    - ocaml
setup      : |
    %make configure
build      : |
    %make
install    : |
    %make_install
