name       : ocamlbuild
version    : 0.11.0
release    : 2
source     :
    - https://github.com/ocaml/ocamlbuild/archive/0.11.0.tar.gz : 1717edc841c9b98072e410f1b0bc8b84444b4b35ed3b4949ce2bec17c60103ee
license    : LGPL-2.1
component  : programming.tools
summary    : OCamlbuild is a generic build tool, that has built-in rules for building OCaml library and programs.
description: |
    OCamlbuild is a generic build tool, that has built-in rules for building OCaml library and programs.
builddeps  :
    - ocaml
rundeps    :
    - ocaml
setup      : |
    %make configure
build      : |
    %make
install    : |
    %make_install
